
server:
  port: 9000

logging:
  level:
    root: info

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring:
  #jsp setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # database setting
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

