
server:
  port: 9000

logging:
  level:
    root: info  # spring all log
    com.spring.mvcproject: debug

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring:
  #jsp setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # database setting
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

# MyBatis setting
mybatis:
  # sql file location
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.spring.mvcproject.database.mybatis
  configuration:
    map-underscore-to-camel-case: true
